openapi: 3.0.0
info:
  description: xendit-invoice-service descriptions
  title: xendit-invoice-service
  version: 1.5.0
servers:
- description: Xendit API Server
  url: https://api.xendit.co
paths:
  /v2/invoices/:
    post:
      operationId: createInvoice
      requestBody:
        content:
          application/json:
            examples:
              Create Invoice Request:
                value:
                  external_id: test1234
                  description: Test Invoice
                  amount: 10000
                  invoice_duration: 172800
                  currency: IDR
                  reminder_time: 1
            schema:
              $ref: '#/components/schemas/CreateInvoiceRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                Successfully created Invoice:
                  $ref: '#/components/examples/InvoiceExample'
                  value: null
              schema:
                $ref: '#/components/schemas/Invoice'
          description: OK
        "400":
          content:
            application/json:
              examples:
                Maximum Transfer Amount Error:
                  value:
                    error_code: MAXIMUM_TRANSFER_AMOUNT_ERROR
                    message: "The maximum amount for using this payment is ${currency}\
                      \ 5,000,000"
                No Collections Method Error:
                  value:
                    error_code: NO_COLLECTION_METHODS_ERROR
                    message: Could not create invoice without any active payment channels
                Email Format Error:
                  summary: EMAIL_FORMAT_ERROR
                  value:
                    error_code: EMAIL_FORMAT_ERROR
                    message: Customer email format is invalid
                Unavailable Payment Error:
                  value:
                    error_code: UNAVAILABLE_PAYMENT_METHOD_ERROR
                    message: The payment method choices did not match with the available
                      one on this business
                Unsupported Currency Error:
                  value:
                    error_code: UNSUPPORTED_CURRENCY
                    message: The payment currency request is not supported for this
                      payment channel
                Currency Mismatch Error:
                  summary: Invoice settings not found for this currency'
                  value:
                    error_code: MISMATCH_CURRENCY_ERROR
                    message: ""
                Invalid Remind Time Error:
                  value:
                    error_code: INVALID_REMINDER_TIME
                    message: The reminder time is invalid
                Invoice Amount Mismatch:
                  value:
                    error_code: INVOICE_AMOUNT_MISMATCHED_CLOSED_VA_EXPECTED_AMOUNT
                    message: Could not create invoice due to invoice amount is not
                      match with Closed VA expected amount."
              schema:
                $ref: '#/components/schemas/BadRequestError'
          description: Bad request
        "401":
          content:
            application/json:
              examples:
                Invalid API Key:
                  $ref: '#/components/examples/InvalidApiKeyExample'
                  value: null
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
          description: Unauthorized
        "403":
          content:
            application/json:
              examples:
                Access Suspended:
                  $ref: '#/components/examples/AccessSuspendedErrorExample'
                  value: null
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: Forbidden
        "404":
          content:
            application/json:
              examples:
                Callback Virtual Account Error:
                  value:
                    error_code: CALLBACK_VIRTUAL_ACCOUNT_NOT_FOUND_ERROR
                    message: Could not find callback virtual account
                Unique Account Number Error:
                  value:
                    error_code: UNIQUE_ACCOUNT_NUMBER_UNAVAILABLE_ERROR
                    message: There is no available virtual account in your non-fixed
                      virtual account range
                Payment Code Not Available:
                  value:
                    error_code: PAYMENT_CODE_NOT_AVAILABLE_ERROR
                    message: No more vacant space for convenience store code
              schema:
                $ref: '#/components/schemas/InvoiceNotFoundError'
          description: Not found
      security:
      - {}
      summary: Create an invoice
      tags:
      - invoice
  /v2/invoices/{invoice_id}:
    get:
      operationId: getInvoiceById
      parameters:
      - description: Invoice ID
        explode: false
        in: path
        name: invoice_id
        required: true
        schema:
          example: 62efe4c33e45294d63f585f2
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
          description: OK
        "401":
          content:
            application/json:
              examples:
                Invalid API Key:
                  $ref: '#/components/examples/InvalidApiKeyExample'
                  value: null
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
          description: Unauthorized
        "404":
          content:
            application/json:
              examples:
                Invoice not found:
                  $ref: '#/components/examples/InvoiceNotFoundErrorExample'
                  value: null
              schema:
                $ref: '#/components/schemas/InvoiceError404ResponseDefinition'
          description: Not found
        "500":
          content:
            application/json:
              examples:
                Internal Server error:
                  $ref: '#/components/examples/ServerErrorExample'
                  value: null
              schema:
                $ref: '#/components/schemas/ServerError'
          description: Internal server error
      security:
      - {}
      summary: Get invoice by invoice id
      tags:
      - invoice
  /v2/invoices:
    get:
      operationId: getInvoices
      parameters:
      - explode: true
        in: query
        name: external_id
        required: false
        schema:
          example: test-external
          type: string
        style: form
      - explode: true
        in: query
        name: statuses
        required: false
        schema:
          example:
          - PENDING
          - SETTLED
          items:
            $ref: '#/components/schemas/InvoiceStatus'
          type: array
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          example: 10
          type: number
        style: form
      - explode: true
        in: query
        name: created_after
        required: false
        schema:
          $ref: '#/components/schemas/Datetime'
        style: form
      - explode: true
        in: query
        name: created_before
        required: false
        schema:
          $ref: '#/components/schemas/Datetime'
        style: form
      - explode: true
        in: query
        name: paid_after
        required: false
        schema:
          $ref: '#/components/schemas/Datetime'
        style: form
      - explode: true
        in: query
        name: paid_before
        required: false
        schema:
          $ref: '#/components/schemas/Datetime'
        style: form
      - explode: true
        in: query
        name: expired_after
        required: false
        schema:
          $ref: '#/components/schemas/Datetime'
        style: form
      - explode: true
        in: query
        name: expired_before
        required: false
        schema:
          $ref: '#/components/schemas/Datetime'
        style: form
      - explode: true
        in: query
        name: last_invoice
        required: false
        schema:
          example: 62efe4c33e45294d63f585f2
          type: string
        style: form
      - explode: true
        in: query
        name: client_types
        required: false
        schema:
          example:
          - API_GATEWAY
          - DASHBOARD
          items:
            $ref: '#/components/schemas/InvoiceClientType'
          type: array
        style: form
      - explode: true
        in: query
        name: payment_channels
        required: false
        schema:
          example:
          - BNI
          - BRI
          items:
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: on_demand_link
        required: false
        schema:
          example: test-link
          type: string
        style: form
      - explode: true
        in: query
        name: recurring_payment_id
        required: false
        schema:
          example: 62efe4c33e45294d63f585f2
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Invoice'
                type: array
          description: OK
        "401":
          content:
            application/json:
              examples:
                INVALID_API_KEY:
                  summary: INVALID_API_KEY
                  value:
                    error_code: INVALID_API_KEY
                    message: Your API key is invalid
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
          description: Unauthorized
        "500":
          content:
            application/json:
              examples:
                Internal Server error:
                  $ref: '#/components/examples/ServerErrorExample'
                  value: null
              schema:
                $ref: '#/components/schemas/ServerError'
          description: Internal server error
      security:
      - {}
      summary: Get all Invoices
      tags:
      - invoice
  /invoices/{invoice_id}/expire!:
    post:
      operationId: expireInvoice
      parameters:
      - description: Invoice ID to be expired
        explode: false
        in: path
        name: invoice_id
        required: true
        schema:
          example: 5f4708b7bd394b0400b96276
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                Successfully expire Invoice:
                  $ref: '#/components/examples/InvoiceExample'
                  value: null
              schema:
                $ref: '#/components/schemas/Invoice'
          description: OK
        "404":
          content:
            application/json:
              examples:
                Invoice not found:
                  $ref: '#/components/examples/InvoiceNotFoundErrorExample'
                  value: null
              schema:
                $ref: '#/components/schemas/InvoiceNotFoundError'
          description: Not found
        "500":
          content:
            application/json:
              examples:
                Internal Server error:
                  $ref: '#/components/examples/ServerErrorExample'
                  value: null
              schema:
                $ref: '#/components/schemas/ServerError'
          description: Internal server error
      security:
      - {}
      summary: Manually expire an invoice
      tags:
      - invoice
components:
  examples:
    InvoiceExample:
      summary: Example of Invoice
      value:
        id: 64e44c42cf6ba3554184a337
        external_id: invoice-1692683329
        user_id: 5f4708b7bd394b0400b96276
        status: PENDING
        merchant_name: Boxify
        merchant_profile_picture_url: https://xnd-companies.s3.amazonaws.com/prod/1633484308963_880.jpg
        amount: 1800000
        payer_email: customer@domain.com
        description: "Invoice Demo #123"
        expiry_date: 2023-08-22T07:48:50.150Z
        invoice_url: https://checkout-staging.xendit.co/v2/64e44c42cf6ba3554184a337
        available_banks:
        - bank_code: MANDIRI
          collection_type: POOL
          transfer_amount: 1800000
          bank_branch: Virtual Account
          account_holder_name: BOXIFY
        - bank_code: BRI
          collection_type: POOL
          transfer_amount: 1800000
          bank_branch: Virtual Account
          account_holder_name: BOXIFY
        - bank_code: BNI
          collection_type: POOL
          transfer_amount: 1800000
          bank_branch: Virtual Account
          account_holder_name: BOXIFY
        - bank_code: PERMATA
          collection_type: POOL
          transfer_amount: 1800000
          bank_branch: Virtual Account
          account_holder_name: BOXIFY
        - bank_code: BCA
          collection_type: POOL
          transfer_amount: 1800000
          bank_branch: Virtual Account
          account_holder_name: BOXIFY
        - bank_code: BSI
          collection_type: POOL
          transfer_amount: 1800000
          bank_branch: Virtual Account
          account_holder_name: BOXIFY
        - bank_code: BJB
          collection_type: POOL
          transfer_amount: 1800000
          bank_branch: Virtual Account
          account_holder_name: BOXIFY
        - bank_code: CIMB
          collection_type: POOL
          transfer_amount: 1800000
          bank_branch: Virtual Account
          account_holder_name: BOXIFY
        - bank_code: SAHABAT_SAMPOERNA
          collection_type: POOL
          transfer_amount: 1800000
          bank_branch: Virtual Account
          account_holder_name: BOXIFY
        - bank_code: BNC
          collection_type: POOL
          transfer_amount: 1800000
          bank_branch: Virtual Account
          account_holder_name: BOXIFY
        available_retail_outlets:
        - retail_outlet_name: ALFAMART
        - retail_outlet_name: INDOMARET
        available_ewallets:
        - ewallet_type: OVO
        - ewallet_type: DANA
        - ewallet_type: SHOPEEPAY
        - ewallet_type: LINKAJA
        - ewallet_type: ASTRAPAY
        - ewallet_type: NEXCASH
        - ewallet_type: JENIUSPAY
        available_qr_codes:
        - qr_code_type: QRIS
        available_direct_debits:
        - direct_debit_type: DD_BRI
        - direct_debit_type: DD_BCA_KLIKPAY
        - direct_debit_type: DD_MANDIRI
        available_paylaters:
        - paylater_type: KREDIVO
        - paylater_type: UANGME
        - paylater_type: AKULAKU
        - paylater_type: ATOME
        should_exclude_credit_card: false
        should_send_email: false
        created: 2023-08-22T05:48:51.105Z
        updated: 2023-08-22T05:48:51.105Z
        currency: IDR
        reminder_date: 2023-08-22T06:48:50.150Z
        customer_notification_preference:
          invoice_created:
          - email
          invoice_paid:
          - email
    InvalidApiKeyExample:
      summary: Example of Invalid API Key error
      value:
        error_code: INVALID_API_KEY
        message: Your API key is invalid
    AccessSuspendedErrorExample:
      summary: Example of Access Suspended error
      value:
        error_code: ACCESS_SUSPENDED
        message: "Access to API has been suspended temporarily due to indication of\
          \ fraudulent activities. If you believe this is inaccurate, kindly contact\
          \ our Customer Success for resolution."
    InvoiceNotFoundErrorExample:
      summary: Example of Invoice not found error
      value:
        error_code: INVOICE_NOT_FOUND_ERROR
        message: Invoice not found.
    ServerErrorExample:
      summary: Example of Server Error
      value:
        error_code: INTERNAL_SERVER_ERROR
        message: Something unxpected happened.
  schemas:
    UnauthorizedError:
      description: An error object used to indicate unauthorized access to an invoice-related
        resource.
      properties:
        error_code:
          description: The specific error code associated with the unauthorized access.
          enum:
          - INVALID_API_KEY
          type: string
        message:
          description: A human-readable error message providing additional context
            about the unauthorized access.
          type: string
      required:
      - error_code
      - message
      type: object
    ForbiddenError:
      description: An error object used to indicate a 403 Forbidden response related
        to invoice operations.
      properties:
        error_code:
          description: The specific error code indicating that access to the invoice
            operation is suspended.
          enum:
          - ACCESS_SUSPENDED
          type: string
        message:
          description: A human-readable error message providing additional context
            about the 403 Forbidden response.
          type: string
      required:
      - error_code
      - message
      type: object
    InvoiceError404ResponseDefinition:
      description: "An error object used to indicate that the requested resource,\
        \ in this case, an invoice, was not found."
      properties:
        error_code:
          description: The specific error code indicating that the requested invoice
            was not found.
          enum:
          - INVOICE_NOT_FOUND_ERROR
          type: string
        message:
          description: A human-readable error message providing additional context
            about the resource not being found.
          type: string
      required:
      - error_code
      - message
      type: object
    Datetime:
      description: Representing a date and time in ISO 8601 format.
      example: 2016-08-29T09:12:33.001Z
      format: date-time
      type: string
    NotificationChannel:
      description: Representing a notification channel for sending messages.
      enum:
      - email
      - sms
      - whatsapp
      - viber
      type: string
    InvoiceStatus:
      description: Representing the status of an invoice.
      enum:
      - PENDING
      - PAID
      - SETTLED
      - EXPIRED
      type: string
    InvoiceCurrency:
      description: Representing the currency used for an invoice.
      enum:
      - IDR
      - USD
      - PHP
      type: string
    InvoiceClientType:
      description: Representing the client type or source of an invoice.
      enum:
      - DASHBOARD
      - API_GATEWAY
      - INTEGRATION
      - ON_DEMAND
      - RECURRING
      - MOBILE
      type: string
    InvoicePaymentMethod:
      description: Representing the payment method used for an invoice.
      enum:
      - POOL
      - CALLBACK_VIRTUAL_ACCOUNT
      - CREDIT_CARD
      - RETAIL_OUTLET
      - QR_CODE
      - QRIS
      - EWALLET
      - DIRECT_DEBIT
      - BANK_TRANSFER
      - PAYLATER
      type: string
    BankCode:
      description: Representing the available bank channels used for invoice-related
        transactions.
      enum:
      - BCA
      - BNI
      - BRI
      - MANDIRI
      - PERMATA
      - BSI
      - BJB
      type: string
    RetailOutletName:
      description: Representing the available retail outlet channels used for invoice-related
        transactions.
      enum:
      - ALFAMART
      - INDOMARET
      - 7ELEVEN
      - CEBUANA
      - DP_ECPAY_LOAN
      - DP_MLHUILLIER
      - DP_PALAWAN
      - DP_ECPAY_SCHOOL
      - LBC
      type: string
    EwalletType:
      description: Representing the available eWallet channels used for invoice-related
        transactions.
      enum:
      - OVO
      - DANA
      - LINKAJA
      - PAYMAYA
      - SHOPEEPAY
      - GCASH
      - GRABPAY
      type: string
    QrCodeType:
      description: Representing the available QR Code channels used for invoice-related
        transactions.
      enum:
      - QRIS
      - PROMPTPAY
      type: string
    DirectDebitType:
      description: Representing the available Direct Debit channels used for invoice-related
        transactions.
      enum:
      - BA_BRI
      - DC_BRI
      - DD_BRI
      - DD_MANDIRI
      - BA_BPI
      - DC_BPI
      - DD_BPI
      - BA_UBP
      - DC_UBP
      - DD_UBP
      - BCA_KLIKPAY
      - BA_BCA_KLIKPAY
      - DC_BCA_KLIKPAY
      - DD_BCA_KLIKPAY
      type: string
    PaylaterType:
      description: Representing the available paylater channels used for invoice-related
        transactions.
      enum:
      - KREDIVO
      - AKULAKU
      - UANGME
      - BILLEASE
      - CASHALO
      - ATOME
      type: string
    AddressObject:
      description: An object representing an address with various properties.
      example:
        country: country
        province: province
        city: city
        street_line2: street_line2
        street_line1: street_line1
        state: state
        postal_code: postal_code
      properties:
        country:
          description: The country where the address is located.
          nullable: true
          type: string
        street_line1:
          description: The first line of the street address.
          nullable: true
          type: string
        street_line2:
          description: The second line of the street address.
          nullable: true
          type: string
        city:
          description: The city or locality within the address.
          nullable: true
          type: string
        province:
          description: The province or region within the country.
          nullable: true
          type: string
        state:
          description: The state or administrative division within the country.
          nullable: true
          type: string
        postal_code:
          description: The postal code or ZIP code for the address.
          nullable: true
          type: string
      type: object
    CustomerObject:
      description: "An object representing a customer with various properties, including\
        \ addresses."
      example:
        addresses:
        - country: country
          province: province
          city: city
          street_line2: street_line2
          street_line1: street_line1
          state: state
          postal_code: postal_code
        - country: country
          province: province
          city: city
          street_line2: street_line2
          street_line1: street_line1
          state: state
          postal_code: postal_code
        surname: surname
        phone_number: phone_number
        id: id
        given_names: given_names
        mobile_number: mobile_number
        customer_id: customer_id
        email: email
      properties:
        id:
          description: The unique identifier for the customer.
          nullable: true
          type: string
        phone_number:
          description: The customer's phone number.
          nullable: true
          type: string
        given_names:
          description: The customer's given names or first names.
          nullable: true
          type: string
        surname:
          description: The customer's surname or last name.
          nullable: true
          type: string
        email:
          description: The customer's email address.
          nullable: true
          type: string
        mobile_number:
          description: The customer's mobile phone number.
          nullable: true
          type: string
        customer_id:
          description: An additional identifier for the customer.
          nullable: true
          type: string
        addresses:
          description: An array of addresses associated with the customer.
          items:
            $ref: '#/components/schemas/AddressObject'
          nullable: true
          type: array
      type: object
    NotificationPreference:
      description: An object representing notification preferences for different invoice
        events.
      example:
        invoice_expired:
        - null
        - null
        invoice_paid:
        - null
        - null
        invoice_reminder:
        - null
        - null
        invoice_created:
        - null
        - null
      properties:
        invoice_created:
          description: Notification channels for when an invoice is created.
          items:
            $ref: '#/components/schemas/NotificationChannel'
          type: array
        invoice_reminder:
          description: Notification channels for invoice reminders.
          items:
            $ref: '#/components/schemas/NotificationChannel'
          type: array
        invoice_expired:
          description: Notification channels for expired invoices.
          items:
            $ref: '#/components/schemas/NotificationChannel'
          type: array
        invoice_paid:
          description: Notification channels for when an invoice is paid.
          items:
            $ref: '#/components/schemas/NotificationChannel'
          type: array
      type: object
    AlternativeDisplayItem:
      description: An object representing alternative display of a VA.
      example:
        type: type
        value: value
      properties:
        type:
          description: Represent type of alternative display.
          type: string
        value:
          description: Represent value of alternative display value.
          type: string
      type: object
    Bank:
      description: An object representing bank details for invoices.
      example:
        bank_code: null
        bank_branch: bank_branch
        bank_account_number: bank_account_number
        transfer_amount: 6.027456183070403
        account_holder_name: account_holder_name
        alternative_displays:
        - type: type
          value: value
        - type: type
          value: value
        collection_type: collection_type
      properties:
        bank_code:
          $ref: '#/components/schemas/BankCode'
        collection_type:
          description: The collection type for the bank details.
          type: string
        bank_branch:
          description: The branch of the bank.
          type: string
        bank_account_number:
          description: The bank account number.
          type: string
        account_holder_name:
          description: The name of the account holder.
          type: string
        transfer_amount:
          description: The transfer amount.
          type: number
        alternative_displays:
          items:
            $ref: '#/components/schemas/AlternativeDisplayItem'
          type: array
      required:
      - account_holder_name
      - bank_code
      - collection_type
      type: object
    RetailOutlet:
      description: An object representing retail outlet details for invoices.
      example:
        retail_outlet_name: null
        transfer_amount: 1.4658129805029452
        merchant_name: merchant_name
        payment_code: payment_code
      properties:
        retail_outlet_name:
          $ref: '#/components/schemas/RetailOutletName'
        payment_code:
          description: The payment code.
          type: string
        transfer_amount:
          description: The transfer amount.
          type: number
        merchant_name:
          description: The name of the merchant.
          type: string
      required:
      - retail_outlet_name
      type: object
    Ewallet:
      description: An object representing e-wallet details for invoices.
      example:
        ewallet_type: null
      properties:
        ewallet_type:
          $ref: '#/components/schemas/EwalletType'
      required:
      - ewallet_type
      type: object
    QrCode:
      description: An object representing QR code details for invoices.
      example:
        qr_code_type: null
      properties:
        qr_code_type:
          $ref: '#/components/schemas/QrCodeType'
      required:
      - qr_code_type
      type: object
    DirectDebit:
      description: An object representing direct debit details for invoices.
      example:
        direct_debit_type: null
      properties:
        direct_debit_type:
          $ref: '#/components/schemas/DirectDebitType'
      required:
      - direct_debit_type
      type: object
    Paylater:
      description: An object representing paylater details for invoices.
      example:
        paylater_type: null
        should_exclude: true
      properties:
        paylater_type:
          $ref: '#/components/schemas/PaylaterType'
        should_exclude:
          description: Indicates whether this paylater option should be excluded.
          type: boolean
      required:
      - paylater_type
      type: object
    InvoiceItem:
      description: An object representing an item within an invoice.
      example:
        quantity: 0.5637376656633328
        reference_id: reference_id
        price: 5.962133916683182
        name: name
        category: category
        url: url
      properties:
        name:
          description: The name of the item.
          type: string
        price:
          description: The price of the item.
          type: number
        quantity:
          description: The quantity of the item. Must be greater than or equal to
            0.
          exclusiveMinimum: true
          minimum: 0
          type: number
        reference_id:
          description: The reference ID of the item.
          type: string
        url:
          description: The URL associated with the item.
          type: string
        category:
          description: The category of the item.
          type: string
      required:
      - name
      - price
      - quantity
      type: object
    InvoiceFee:
      description: An object representing internal details for a fee associated with
        an invoice.
      example:
        type: type
        value: 2.3021358869347655
      properties:
        type:
          description: The type of fee.
          type: string
        value:
          description: The value or amount of the fee.
          type: number
      required:
      - type
      - value
      type: object
    Invoice:
      description: An object representing details for an invoice.
      example:
        available_paylaters:
        - paylater_type: null
          should_exclude: true
        - paylater_type: null
          should_exclude: true
        fees:
        - type: type
          value: 2.3021358869347655
        - type: type
          value: 2.3021358869347655
        payer_email: payer_email
        reminder_date: 2016-08-29T09:12:33.001Z
        description: description
        external_id: external_id
        locale: locale
        should_send_email: true
        customer_notification_preference:
          invoice_expired:
          - null
          - null
          invoice_paid:
          - null
          - null
          invoice_reminder:
          - null
          - null
          invoice_created:
          - null
          - null
        currency: null
        id: id
        failure_redirect_url: failure_redirect_url
        payment_method: null
        amount: 0.8008281904610115
        available_banks:
        - bank_code: null
          bank_branch: bank_branch
          bank_account_number: bank_account_number
          transfer_amount: 6.027456183070403
          account_holder_name: account_holder_name
          alternative_displays:
          - type: type
            value: value
          - type: type
            value: value
          collection_type: collection_type
        - bank_code: null
          bank_branch: bank_branch
          bank_account_number: bank_account_number
          transfer_amount: 6.027456183070403
          account_holder_name: account_holder_name
          alternative_displays:
          - type: type
            value: value
          - type: type
            value: value
          collection_type: collection_type
        available_ewallets:
        - ewallet_type: null
        - ewallet_type: null
        available_retail_outlets:
        - retail_outlet_name: null
          transfer_amount: 1.4658129805029452
          merchant_name: merchant_name
          payment_code: payment_code
        - retail_outlet_name: null
          transfer_amount: 1.4658129805029452
          merchant_name: merchant_name
          payment_code: payment_code
        created: 2016-08-29T09:12:33.001Z
        expiry_date: 2016-08-29T09:12:33.001Z
        merchant_name: merchant_name
        available_qr_codes:
        - qr_code_type: null
        - qr_code_type: null
        available_direct_debits:
        - direct_debit_type: null
        - direct_debit_type: null
        merchant_profile_picture_url: merchant_profile_picture_url
        should_authenticate_credit_card: true
        user_id: user_id
        success_redirect_url: success_redirect_url
        should_exclude_credit_card: true
        updated: 2016-08-29T09:12:33.001Z
        items:
        - quantity: 0.5637376656633328
          reference_id: reference_id
          price: 5.962133916683182
          name: name
          category: category
          url: url
        - quantity: 0.5637376656633328
          reference_id: reference_id
          price: 5.962133916683182
          name: name
          category: category
          url: url
        invoice_url: invoice_url
        status: null
        fixed_va: true
        customer:
          addresses:
          - country: country
            province: province
            city: city
            street_line2: street_line2
            street_line1: street_line1
            state: state
            postal_code: postal_code
          - country: country
            province: province
            city: city
            street_line2: street_line2
            street_line1: street_line1
            state: state
            postal_code: postal_code
          surname: surname
          phone_number: phone_number
          id: id
          given_names: given_names
          mobile_number: mobile_number
          customer_id: customer_id
          email: email
      properties:
        id:
          description: The unique identifier for the invoice.
          type: string
        external_id:
          description: The external identifier for the invoice.
          type: string
        user_id:
          description: The user ID associated with the invoice.
          type: string
        payer_email:
          description: The email address of the payer.
          type: string
        description:
          description: A description of the invoice.
          type: string
        payment_method:
          $ref: '#/components/schemas/InvoicePaymentMethod'
        status:
          $ref: '#/components/schemas/InvoiceStatus'
        merchant_name:
          description: The name of the merchant.
          type: string
        merchant_profile_picture_url:
          description: The URL of the merchant's profile picture.
          type: string
        locale:
          description: The locale or language used for the invoice.
          type: string
        amount:
          description: The total amount of the invoice.
          type: number
        expiry_date:
          description: Representing a date and time in ISO 8601 format.
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
        invoice_url:
          description: The URL to view the invoice.
          type: string
        available_banks:
          description: An array of available banks for payment.
          items:
            $ref: '#/components/schemas/Bank'
          type: array
        available_retail_outlets:
          description: An array of available retail outlets for payment.
          items:
            $ref: '#/components/schemas/RetailOutlet'
          type: array
        available_ewallets:
          description: An array of available e-wallets for payment.
          items:
            $ref: '#/components/schemas/Ewallet'
          type: array
        available_qr_codes:
          description: An array of available QR codes for payment.
          items:
            $ref: '#/components/schemas/QrCode'
          type: array
        available_direct_debits:
          description: An array of available direct debit options for payment.
          items:
            $ref: '#/components/schemas/DirectDebit'
          type: array
        available_paylaters:
          description: An array of available pay-later options for payment.
          items:
            $ref: '#/components/schemas/Paylater'
          type: array
        should_exclude_credit_card:
          description: Indicates whether credit card payments should be excluded.
          type: boolean
        should_send_email:
          description: Indicates whether email notifications should be sent.
          type: boolean
        created:
          description: Representing a date and time in ISO 8601 format.
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
        updated:
          description: Representing a date and time in ISO 8601 format.
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
        success_redirect_url:
          description: The URL to redirect to on successful payment.
          type: string
        failure_redirect_url:
          description: The URL to redirect to on payment failure.
          type: string
        should_authenticate_credit_card:
          description: Indicates whether credit card authentication is required.
          type: boolean
        currency:
          $ref: '#/components/schemas/InvoiceCurrency'
        items:
          description: An array of items included in the invoice.
          items:
            $ref: '#/components/schemas/InvoiceItem'
          type: array
        fixed_va:
          description: Indicates whether the virtual account is fixed.
          type: boolean
        reminder_date:
          description: Representing a date and time in ISO 8601 format.
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
        customer:
          $ref: '#/components/schemas/CustomerObject'
        customer_notification_preference:
          $ref: '#/components/schemas/NotificationPreference'
        fees:
          description: An array of fees associated with the invoice.
          items:
            $ref: '#/components/schemas/InvoiceFee'
          type: array
      required:
      - amount
      - available_banks
      - available_direct_debits
      - available_ewallets
      - available_paylaters
      - available_qr_codes
      - available_retail_outlets
      - created
      - expiry_date
      - external_id
      - invoice_url
      - merchant_name
      - merchant_profile_picture_url
      - should_send_email
      - status
      - status_updated
      - updated
      - user_id
      type: object
    CreateInvoiceRequest:
      description: An object representing for an invoice creation request.
      example:
        external_id: invoice-external-id-1
        amount: 10000
        description: Payment for PSN subscription
      properties:
        external_id:
          description: The external ID of the invoice.
          type: string
        amount:
          description: The invoice amount.
          type: number
        payer_email:
          description: The email address of the payer.
          type: string
        description:
          description: A description of the payment.
          type: string
        invoice_duration:
          description: The duration of the invoice.
          type: string
        callback_virtual_account_id:
          description: The ID of the callback virtual account.
          type: string
        should_send_email:
          description: Indicates whether email notifications should be sent.
          type: boolean
        customer:
          $ref: '#/components/schemas/CustomerObject'
        customer_notification_preference:
          $ref: '#/components/schemas/NotificationPreference'
        success_redirect_url:
          description: The URL to redirect to on successful payment.
          type: string
        failure_redirect_url:
          description: The URL to redirect to on payment failure.
          type: string
        payment_methods:
          description: An array of available payment methods.
          items:
            type: string
          type: array
        mid_label:
          description: The middle label.
          type: string
        should_authenticate_credit_card:
          description: Indicates whether credit card authentication is required.
          type: boolean
        currency:
          description: The currency of the invoice.
          type: string
        reminder_time:
          description: The reminder time.
          type: number
        local:
          description: The local.
          type: string
        reminder_time_unit:
          description: The unit of the reminder time.
          type: string
        items:
          description: An array of items included in the invoice.
          items:
            $ref: '#/components/schemas/InvoiceItem'
          type: array
        fees:
          description: An array of fees associated with the invoice.
          items:
            $ref: '#/components/schemas/InvoiceFee'
          type: array
      required:
      - amount
      - external_id
      type: object
    BadRequestError:
      description: Response definition for a 400 Bad Request error when creating an
        invoice.
      properties:
        error_code:
          description: The error code indicating the type of error that occurred.
          enum:
          - MAXIMUM_TRANSFER_AMOUNT_ERROR
          - NO_COLLECTION_METHODS_ERROR
          - EMAIL_FORMAT_ERROR
          - UNAVAILABLE_PAYMENT_METHOD_ERROR
          - UNSUPPORTED_CURRENCY
          - MISMATCH_CURRENCY_ERROR
          - INVALID_REMINDER_TIME
          type: string
        message:
          description: A human-readable error message that provides additional information
            about the error.
          type: string
      required:
      - error_code
      - message
      type: object
    InvoiceNotFoundError:
      description: Response definition for a 404 Not Found error when creating an
        invoice.
      properties:
        error_code:
          description: The error code indicating the type of error that occurred.
          enum:
          - CALLBACK_VIRTUAL_ACCOUNT_NOT_FOUND_ERROR
          - UNIQUE_ACCOUNT_NUMBER_UNAVAILABLE_ERROR
          - PAYMENT_CODE_NOT_AVAILABLE_ERROR
          type: string
        message:
          description: A human-readable error message that provides additional information
            about the error.
          type: string
      required:
      - error_code
      - message
      type: object
    ServerError:
      properties:
        error_code:
          enum:
          - SERVER_ERROR
          type: string
        message:
          type: string
      required:
      - error_code
      - message
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: x-api-key
      type: apiKey
